### ISSUE TITLE
macOS crashes on start up

### ISSUE THREAD

**Issue by marqueone** [agility/Agility-AspNetCore#2]
## Description ##

On macOS when a new project is created and configured with the following configs: 

appsettings.Development.json
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "Agility": {
    "contentCacheFilePath": "/tmp/AgilityContent/",
    "developmentMode": "true",
    "Trace": {
      "traceLevel": "Verbose",
      "logFilePath": "/tmp/AgilityLogs/Website.log"
    }
  }
}
```

appsettings.json
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*",
  "Agility": {
    "applicationName": "Sample Project",
    "websiteName": "**************",
    "securityKey": "**************",
    "contentCacheFilePath": "/tmp/AgilityContent/",
    "contentServerUrl": "https://contentserver1503.agilitycms.com/agilitycontentserver.svc",
    "developmentMode": "true",
    "Trace": {
      "traceLevel": "Warning",
      "logFilePath": "/tmp/AgilityLogs/Website.log"
    },
    "UGC": {
      "Url": "https://ugc.agilitycms.com/",
      "Key": "**************",
      "Password": "**************"
    },
    "Analytics": {
      "Url": ""
    }
  }
}
```

and run for the first time the project will crash and throw the following stack trace: 

```
MO-iMAC01:k12.core.app mikes$ .net run
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/Users/mikes/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Application startup exception: System.ApplicationException: Error occurred in configure:  ---> System.IO.DirectoryNotFoundException: /tmp/AgilityContent/
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Agility.Web.AgilityContext.Configure(IApplicationBuilder app, IHostingEnvironment env, Boolean useResponseCaching)
   --- End of inner exception stack trace ---
   at Agility.Web.AgilityContext.Configure(IApplicationBuilder app, IHostingEnvironment env, Boolean useResponseCaching)
   at k12.core.app.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /Users/mikes/Projects/IMC/k12.core/k12.core.app/Startup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.ApplicationException: Error occurred in configure:  ---> System.IO.DirectoryNotFoundException: /tmp/AgilityContent/
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Agility.Web.AgilityContext.Configure(IApplicationBuilder app, IHostingEnvironment env, Boolean useResponseCaching)
   --- End of inner exception stack trace ---
   at Agility.Web.AgilityContext.Configure(IApplicationBuilder app, IHostingEnvironment env, Boolean useResponseCaching)
   at k12.core.app.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /Users/mikes/Projects/IMC/k12.core/k12.core.app/Startup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: System.ApplicationException: Error occurred in configure:  ---> System.IO.DirectoryNotFoundException: /tmp/AgilityContent/
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Agility.Web.AgilityContext.Configure(IApplicationBuilder app, IHostingEnvironment env, Boolean useResponseCaching)
   --- End of inner exception stack trace ---
   at Agility.Web.AgilityContext.Configure(IApplicationBuilder app, IHostingEnvironment env, Boolean useResponseCaching)
   at k12.core.app.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /Users/mikes/Projects/IMC/k12.core/k12.core.app/Startup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at k12.core.app.Program.Main(String[] args) in /Users/mikes/Projects/IMC/k12.core/k12.core.app/Program.cs:line 17
```

This looks like when the project is run it is not automatically creating the content / log folders correctly. In a windows environment the behaviour is that the missing folders are created if they do not exist but this does not appear to e the case in macOS.

When using the *nix temp folder best practice, this will happen again on reboots due to the nature of the /tmp folder

## System ##
**OS**: macOS Mojave 10.14.3
**DotnetCore**: 2.2
**Agility.AspNetCore**: 0.0.1.11

**Comment by joelvarty** [comment]
You need to make sure the path for content cache is set correctly. Try using ./AgilityContent or a subfolder of your user directory.

Yours -

Joel Varty
CTO, Agility

________________________________

**Comment by marqueone** [comment]
Hey @joelvarty As per suggestion I've tried both approaches, and I still get the same behaviour and the  project crashes on start up because it can't seem to find and create the content and log folders.

```
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/Users/mikes/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Application startup exception: System.ApplicationException: Error occurred in configure:  ---> System.IO.DirectoryNotFoundException: /Users/mikes/Projects/IMC/k12.core/k12.core.app/AgilityContent/
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Agility.Web.AgilityContext.Configure(IApplicationBuilder app, IHostingEnvironment env, Boolean useResponseCaching)
   --- End of inner exception stack trace ---
   at Agility.Web.AgilityContext.Configure(IApplicationBuilder app, IHostingEnvironment env, Boolean useResponseCaching)
   at k12.core.app.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /Users/mikes/Projects/IMC/k12.core/k12.core.app/Startup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.ApplicationException: Error occurred in configure:  ---> System.IO.DirectoryNotFoundException: /Users/mikes/Projects/IMC/k12.core/k12.core.app/AgilityContent/
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Agility.Web.AgilityContext.Configure(IApplicationBuilder app, IHostingEnvironment env, Boolean useResponseCaching)
   --- End of inner exception stack trace ---
   at Agility.Web.AgilityContext.Configure(IApplicationBuilder app, IHostingEnvironment env, Boolean useResponseCaching)
   at k12.core.app.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /Users/mikes/Projects/IMC/k12.core/k12.core.app/Startup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: System.ApplicationException: Error occurred in configure:  ---> System.IO.DirectoryNotFoundException: /Users/mikes/Projects/IMC/k12.core/k12.core.app/AgilityContent/
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Agility.Web.AgilityContext.Configure(IApplicationBuilder app, IHostingEnvironment env, Boolean useResponseCaching)
   --- End of inner exception stack trace ---
   at Agility.Web.AgilityContext.Configure(IApplicationBuilder app, IHostingEnvironment env, Boolean useResponseCaching)
   at k12.core.app.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /Users/mikes/Projects/IMC/k12.core/k12.core.app/Startup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at k12.core.app.Program.Main(String[] args) in /Users/mikes/Projects/IMC/k12.core/k12.core.app/Program.cs:line 17
```

**Comment by joelvarty** [comment]
I don’t remember having to set write permissions, but maybe try that in Finder

Yours -

Joel Varty
CTO, Agility

________________________________

**Comment by joelvarty** [comment]
As a point of interest, here is what my appSetting.Development.json looks like:
`{
"Agility": {
    "contentCacheFilePath": "/Users/joelvarty/Documents/ReactWebsite-1/AgilityContent/",
    "developmentMode": "false",
    "Trace": {
      "traceLevel": "Verbose",
      "logFilePath": "/Users/joelvarty/Documents/ReactWebsite-1/AgilityLogs/AgilityWebsite.log"
    }
}  
}`

**Comment by joelvarty** [comment]
This issue has been solved, I believe.
